#!/usr/bin/env bash
set -euo pipefail

REPORT="storage/app/resource-detail-capability-matrix-report.md"
mkdir -p "$(dirname "$REPORT")"

{
  echo "# Resource Detail Capability Matrix Report"
  echo
  echo "Generated by \`patches/probe_resource_detail_capability_matrix.sh\`."
  echo
  echo "Purpose: discover detail-page capabilities used by existing Concord/ErpSmart modules so the future AI Module Builder can expose them as selectable feature toggles."
  echo
  echo "## Snapshot"
  echo
  echo "- Date: $(date --iso-8601=seconds 2>/dev/null || date)"
  echo "- PWD: $(pwd)"
  echo "- Git branch: $(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo unknown)"
  echo

  echo "## Backend resource contracts"
  echo
  echo '```text'
  find modules -path '*/app/Resources/*.php' -type f -maxdepth 5 2>/dev/null \
    | sort \
    | xargs -r grep -nE 'class .* extends Resource implements|Mediable|Importable|Exportable|Cloneable|Tableable|WithResourceRoutes|AcceptsCustomFields|HasEmail|BillableResource|PipesComments|AssociatesResources|Timeline|Changelog|HasDocuments' || true
  echo '```'
  echo

  echo "## Models with reusable detail traits"
  echo
  echo '```text'
  grep -RInE 'use .*HasMedia|HasDocuments|HasTimeline|LogsModelPivotChanges|Resourceable|HasComments|BelongsTo\(|morphToMany\(|morphedByMany\(' modules/*/app/Models modules/*/app/Concerns 2>/dev/null || true
  echo '```'
  echo

  echo "## Resource panels and detail tabs"
  echo
  echo '```text'
  grep -RInE "Panel::make|RecordTab|resource-media-panel|ResourceMediaPanel|RecordTab.*Panel|timelineRelation|RelatedDocument|RelatedEmail|RecordTabActivity|RecordTabCall|RecordTabNote|RecordTabDocument" modules/*/app/Resources modules/*/resources/js resources/js 2>/dev/null || true
  echo '```'
  echo

  echo "## Media / attachment components"
  echo
  echo '```text'
  grep -RInE "MediaUpload|MediaItemsList|ResourceRecordMediaList|ResourceMediaPanel|delete.*media|remove.*media|api/.*media|/media/" modules/Core/resources/js modules/*/resources/js 2>/dev/null || true
  echo '```'
  echo

  echo "## Action classes and row/detail actions"
  echo
  echo '```text'
  find modules -path '*/app/Actions/*.php' -type f -maxdepth 5 2>/dev/null | sort | sed -n '1,240p'
  echo '```'
  echo

  echo "## Candidate Builder feature toggles"
  echo
  cat <<'EOF'

- resource.crud
- resource.table
- resource.permissions
- resource.custom_fields
- resource.import
- resource.export
- resource.clone
- resource.delete
- resource.detail_page
- resource.detail.inline_edit
- resource.detail.timeline
- resource.detail.changelog
- resource.detail.notes
- resource.detail.attachments
- resource.detail.documents
- resource.detail.activities
- resource.detail.emails
- resource.detail.calls
- resource.detail.comments
- resource.detail.related_records
- resource.detail.workflow_triggers
- resource.detail.audit_log
- resource.detail.cards_kpis
EOF
} > "$REPORT"

echo "Report written to: $REPORT"
