#!/usr/bin/env bash
set -euo pipefail

REPORT="storage/app/warehouse-documents-contract-report.md"
mkdir -p "$(dirname "$REPORT")"

section() {
  echo "" >> "$REPORT"
  echo "## $1" >> "$REPORT"
  echo "" >> "$REPORT"
}

run() {
  local title="$1"
  shift
  section "$title"
  echo '```bash' >> "$REPORT"
  printf '%q ' "$@" >> "$REPORT"
  echo >> "$REPORT"
  echo '```' >> "$REPORT"
  echo >> "$REPORT"
  echo '```text' >> "$REPORT"
  "$@" >> "$REPORT" 2>&1 || true
  echo '```' >> "$REPORT"
}

cat > "$REPORT" <<'MD'
# Warehouse Documents / Attachments Contract Report

Generated by `patches/probe_warehouse_documents_contract.sh`.

Purpose: discover how this exact ErpSmart/ConcordCRM codebase wires documents, media, files and record tabs before adding the feature to Warehouse.

MD

section "Project snapshot"
{
  echo "- Date: $(date -Iseconds)"
  echo "- PWD: $(pwd)"
  echo "- Git branch: $(git branch --show-current 2>/dev/null || true)"
  echo "- PHP: $(php -v | head -1 2>/dev/null || true)"
  echo "- Node package manager files: $(ls package.json package-lock.json pnpm-lock.yaml yarn.lock 2>/dev/null | tr '\n' ' ')"
} >> "$REPORT"

run "Resource contracts directory" find modules/Core/app -path '*Contracts*Resources*' -type f -maxdepth 8
run "Resource capability contracts containing media/document keywords" grep -RInE "interface .*Mediable|Mediable|Media|Document|Attachment|File" modules/Core/app modules/*/app 2>/dev/null
run "Frontend record-tab components" find modules resources -path '*resources/js*' -type f \( -name '*RecordTab*' -o -name '*Document*' -o -name '*Media*' -o -name '*File*' -o -name '*Attachment*' \) 2>/dev/null
run "Frontend imports/usages of document/media tabs" grep -RInE "RecordTab(Document|Media|File|Attachment)|DocumentTab|MediaTab|Attachments|attachments|media_count|documents_count|timelineRelation" modules resources 2>/dev/null
run "Backend models with documents/media/file relations" grep -RInE "function (documents|media|attachments|files)\(|morph(ToMany|Many)|morphedByMany|InteractsWithMedia|HasMedia|mediable|documentable|fileable|attachable" modules/*/app modules/Core/app 2>/dev/null
run "Database migrations for document/media pivots" grep -RInE "documentable|mediable|media|attachments|files|fileable|noteable" database modules/*/database modules/Core/database 2>/dev/null
run "API routes containing documents/media/files" sh -lc "php artisan route:list 2>/dev/null | grep -Ei 'documents|media|files|attachments|upload|warehouses'"
run "Warehouse current files" sh -lc "sed -n '1,240p' modules/Warehouse/app/Resources/Warehouse.php; printf '\n--- MODEL ---\n'; sed -n '1,220p' modules/Warehouse/app/Models/Warehouse.php; printf '\n--- VIEW ---\n'; sed -n '1,260p' modules/Warehouse/resources/js/views/WarehousesView.vue"
run "Package dependencies related to media/files" sh -lc "cat composer.json package.json 2>/dev/null | grep -Ei 'media|file|upload|document|spatie|tinymce|dropzone'"

section "Interpretation checklist for the AI agent"
cat >> "$REPORT" <<'MD'

Use this checklist before writing the next patch:

1. If Core has `Modules\Core\Contracts\Resources\Mediable`, inspect its expected model trait and endpoint behavior.
2. If existing profile pages use a `RecordTab*` component for files/media/documents, copy that frontend contract exactly.
3. If the Documents module represents proposal/quote/agreement workflow, do not use it as generic warehouse attachments unless the business explicitly wants CRM documents on Warehouse.
4. Prefer generic media/attachments for ERP master data evidence such as warehouse photos, lease files, permits, inventory sheets and internal documents.
5. If a pivot table exists without timestamps, do not add `withTimestamps()` to relations unless the table has `created_at` and `updated_at`.
6. Do not use `resolveRelationUsing()` for inverse relations that are persisted through Core `AssociatesResources`; pivot events need a concrete method name.
7. Add SmartDocs/RAG entries for every discovered contract and every failed assumption.

MD

echo "Report written to: $REPORT"
