services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: erpsmart_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
      - redis
    networks:
      - erpsmart

  nginx:
    image: nginx:1.27-alpine
    container_name: erpsmart_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - erpsmart

  mysql:
    image: mysql:8.0
    container_name: erpsmart_mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: erpsmart
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: erpsmart
      MYSQL_PASSWORD: erpsmart
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - erpsmart

  redis:
    image: redis:7-alpine
    container_name: erpsmart_redis
    ports:
      - "6379:6379"
    networks:
      - erpsmart

  node:
    image: node:20-bookworm-slim
    container_name: erpsmart_node
    working_dir: /var/www/html
    ports:
        - "5173:5173"
    volumes:
        - .:/var/www/html
        - erpsmart-node-modules:/var/www/html/node_modules
    environment:
        CHOKIDAR_USEPOLLING: "true"
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    networks:
        - erpsmart


  scheduler:
    image: erpsmart-app
    container_name: erpsmart_scheduler
    working_dir: /var/www/html
    volumes:
     - .:/var/www/html
    command: sh -c "while true; do php artisan schedule:run --verbose --no-interaction; sleep 60; done"
    depends_on:
      - app
      - mysql
      - redis
    networks:
      - erpsmart

  queue:
    image: erpsmart-app
    container_name: erpsmart_queue
    working_dir: /var/www/html
    volumes:
        - .:/var/www/html
    command: sh -c "php artisan queue:work --verbose --tries=3 --timeout=120"
    depends_on:
        - app
        - mysql
        - redis
    networks:
        - erpsmart


networks:
  erpsmart:
    driver: bridge

volumes:
  mysql_data:
  erpsmart-node-modules:




