<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Remove stale Warehouse-related permissions created during early MVP iterations.
     *
     * The permissions UI is generated from registered permission groups, but Spatie
     * permission records are persisted. Earlier Warehouse iterations registered
     * experimental/export permissions with generic labels. This migration keeps the
     * canonical Warehouse permission matrix and removes only non-canonical
     * permissions whose names explicitly reference warehouse/warehouses.
     */
    public function up(): void
    {
        $canonical = [
            'view all warehouses',
            'create warehouses',
            'edit all warehouses',
            'delete any warehouse',
            'bulk delete warehouses',
            'export warehouses',
            'import warehouses',
        ];

        $stalePermissionIds = DB::table('permissions')
            ->where(function ($query) {
                $query->where('name', 'like', '%warehouse%')
                    ->orWhere('name', 'like', '%warehouses%');
            })
            ->whereNotIn('name', $canonical)
            ->pluck('id');

        if ($stalePermissionIds->isNotEmpty()) {
            DB::table('role_has_permissions')
                ->whereIn('permission_id', $stalePermissionIds)
                ->delete();

            DB::table('model_has_permissions')
                ->whereIn('permission_id', $stalePermissionIds)
                ->delete();

            DB::table('permissions')
                ->whereIn('id', $stalePermissionIds)
                ->delete();
        }

        foreach ($canonical as $permission) {
            DB::table('permissions')->updateOrInsert(
                [
                    'name' => $permission,
                    'guard_name' => 'sanctum',
                ],
                [
                    'updated_at' => now(),
                    'created_at' => now(),
                ]
            );
        }
    }

    public function down(): void
    {
        // Intentionally left empty. Deleted stale permissions were generated by
        // early development iterations and should not be restored.
    }
};
