<?php

return [
    'warehouse' => 'Warehouse',
    'warehouses' => 'Warehouses',
    'create' => 'Create Warehouse',
    'edit' => 'Edit Warehouse',
    'created' => 'Warehouse created successfully.',
    'updated' => 'Warehouse updated successfully.',
    'active' => 'Active',
    'inactive' => 'Inactive',
    'back_to_warehouses' => 'Back to warehouses',

    'actions' => [
        'customize_fields' => 'Customize fields',
        'manage_permissions' => 'Manage permissions',
    ],

    'empty_state' => [
        'title' => 'Create your first warehouse',
        'description' => 'Warehouses are the first inventory building block. Start by creating a warehouse, then later connect locations, products, stock movements, transfers, and inventory reports.',
    ],

    'permissions' => [
        'view_all' => 'View all warehouses',
        'create' => 'Create warehouses',
        'edit_all' => 'Edit all warehouses',
        'delete_any' => 'Delete any warehouse',
        'bulk_delete' => 'Bulk delete warehouses',
        'export' => 'Export warehouses',
        'import' => 'Import warehouses',
    ],

    'custom_fields' => [
        'title' => 'Warehouse custom fields',
        'description' => 'Define extra warehouse attributes without changing the source code. These fields are stored by the Core custom field system and are available in create, update, detail, table, import, and export flows when enabled in field settings.',
    ],

    'import_export' => [
        'status' => 'Warehouse import and export are enabled through the Core Resource engine.',
        'sample_note' => 'Use Name, Code, Description, and Active columns in CSV imports. Active accepts yes/no, true/false, 1/0, on/off.',
        'duplicate_export_note' => 'If multiple generic Export rows appear in the role UI, inspect the Core permission group views before deleting permissions; these labels may be capability views generated by the Core export system.',
    ],

    'clone' => [
        'name_fallback' => 'Warehouse Copy',
    ],

    'fields' => [
        'name' => 'Name',
        'code' => 'Code',
        'description' => 'Description',
        'is_active' => 'Active',
    ],
];
